project:
  type: website

website:
  title: "jiwasawaのブログ"
  site-url: https://jiwasawa.github.io/blog_jp
  description: "機械学習・AIに関する話題を中心に書いています"
  google-analytics: G-8BXHXPDSCJ
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://x.com/jiwasawa
      - icon: linkedin
        href: https://www.linkedin.com/in/junichiro-iwasawa-875b37130/
      - icon: github
        href: https://github.com/jiwasawa
      - icon: rss
        href: index.xml
lang: ja

format:
  html:
    title-prefix: ""
    theme:
      - cosmo
      - brand
    css: styles.css
execute:
  freeze: auto



